language: node_js
node_js:
- node
install:
- npm i -g npm
- npm ci
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: rCmzF0RgAwQfhqbzPLRSLuVOqaIUZb/s25zEt3Wv1YDr1Jam9ZYZObtqwuCAcEHiXWoIwluprBQ9GylCOmTdKKHyVmslFc9iBdF9EAS9Bjx5gyqXPGMwGWRZS4fCOIJT7lgNOuUf4pNMRxYx4e9vSOqq9rklqZFjWAi2u1/tmNbF/KL7TbEOdqT879j4UD1I/FEufljAjsaqKZJbPMQfv73woo95JPNjkmOdCPinnQmMzJf8Uj9KZ/cxihNpalGAOTEfTb7hSp4GCP+4mMOBIRkRDC/CtdJOpDB+KXSzomVUPN8soEW08mDYXDwmIglb52/y5S1wXfm0mc56SOD3ugTQ31Gf2NxrOBlski5F8QBsEdFuMZOR9onq3/Ezyn5IzAZatl3hs16asaZfHzXHBy46zhmfQR2K/Gzz7UVVRhB4GvJQISitlzoXKpHns4HyYVmXdP5Losn8bKVX2ShBUYAy/5I+48lIVah5QUd3yCptBeTRyTUcjuBrrCrVien9ramNuDAKMNu88uwqETLL5EXFY9AgzXX3Ur2/W4coRH+kcbJCDPtZ7LuTIera3BhsJX2Yvu2PHKwOZWyu/aGqg8UOy9+mert1bOvTp0W6VuN0fzEF3g1KYRG+sc6kRygMQw/E5XUW1LUcjsw2I0rNo7eCwYmoBwGWIJeVdw2pG0g=
notifications:
  email:
  - travis@nevenall.games